name: Snyk Security

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif || true

  code_scanning:
    needs: snyk
    runs-on: windows-latest
    steps:
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
